jaoafa/JDA-VCSpeaker

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/ParamCheck.java
- `<title>`, `</title>` を含んでいてsubstringを間違えてた
- どちらにしても15文字だと少ないので30文字に変更
- デフォルトのスピード読み上げ速度を120に変更した
🙏
> fix: Webページタイトルの読み上げを純粋な30文字に修正・デフォルトの読み上げ速度を120に変更

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
- src/main/java/com/jaoafa/jdavcspeaker/Main.java
close #37 
- プレフィックスを設定ファイル `prefix` キーで設定できるように
- 設定ファイルに `visionAPIKey` キーを追加
- 画像ファイルが投稿され、 `visionAPIKey` が登録されている場合は `画像ファイル「<ラベル名>を含む画像」が送信されました。` と発言
- それ以外の場合は `ファイル「<ファイル名>」が送信されました。` と発言
> feat: VisionAPIを使用した画像ファイルの内容発言機能

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Join.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Move.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/MsgFormatter.java
close #4 
`tomachi が 🧀CheeseFactory(WorkingSpace) に参加しました。` -> `tomachi が CheeseFactory に参加しました。`
> feat: #4 参加・移動・退出時、チャンネル名から絵文字とかっこ内を削除するように

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_GeneralNotify.java
close #16 
- 会話開始時の通知メッセージのIDを `last-notify-id` ファイルに保存
- `last-notify-id` ファイルがあれば、そのメッセージIDのメッセージを取得 → メッセージを削除
> feat: 会話開始時の通知チャンネルに投稿する際、前回の通知メッセージを削除するように

- src/main/java/com/jaoafa/jdavcspeaker/Command/CmdExecutor.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Default.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Ignore.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_VCSpeaker.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/AutoDisconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/AutoJoin.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/AutoMove.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_GeneralNotify.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
- src/main/java/com/jaoafa/jdavcspeaker/Framework/Command/CmdRegister.java
- src/main/java/com/jaoafa/jdavcspeaker/Framework/Event/EventRegister.java
- src/main/java/com/jaoafa/jdavcspeaker/Framework/FunctionHooker.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/CmdBuilders.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibEmbedColor.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibFlow.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibJson.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibReporter.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibTextColor.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibTitle.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/MsgFormatter.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
- src/main/java/com/jaoafa/jdavcspeaker/Main.java
- src/main/java/com/jaoafa/jdavcspeaker/Player/TrackInfo.java
- src/main/java/com/jaoafa/jdavcspeaker/Player/TrackScheduler.java
- `record` の使用 (参考: https://docs.oracle.com/javase/jp/15/language/records.html)
- パターン変数の使用 (参考: https://www.ne.jp/asahi/hishidama/home/tech/java/preview/instanceof.14.html)
- `Optional.isEmpty` の使用
- `TextChannel.sendMessage(MessageEmbed)` から `TextChannel.sendMessageEmbeds(MessageEmbed)` へ変更
- `Message.reply(MessageEmbed)` から `Message.replyEmbeds(MessageEmbed)` へ変更
- `SlashCommandEvent.getOption(String)` の返り値が Nullable なために発生する NullPointerException 対策: `Main.getExistsOption` を作成して置き換え
- `final` に変更できる変数を `final` に変更
- `/vcspeaker server *` コマンドが正常に動いていない不具合の修正
- LibFlowクラスの仕様変更
- 各関数に `@CheckReturnValue` を指定し、最終的に `.run();` しなければならないように（関数チェーン）
- `String.format` から `String.formatted` へ変更
- 使用されていない関数の削除
> fix: インスペクション

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_GoLiveNotify.java
- src/main/java/com/jaoafa/jdavcspeaker/Framework/Command/CmdRegister.java
close #72
- 開始時チャット: :satellite: `ユーザ名` が チャンネル名 でGoLiveを開始しました。
- 終了時チャット: :satellite: `ユーザ名` が チャンネル名 でGoLiveを終了しました。
- 開始時発言（同じチャンネル参加中のみ）: ユーザ名がGoLiveを開始しました。
- 終了時発言（同じチャンネル参加中のみ）: ユーザ名がGoLiveを終了しました。
> feat: #72 GoLive開始時・終了時に通知する

- README.md
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java
- `alias parse text:<text>`: `<text>` に対して設定済みのエイリアスを適用したテキストを返します
> feat: alias parseコマンドの実装

- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
主にエイリアス関連の不具合
エイリアスをかけて、そのエイリアステキストを読ませた後、エイリアスを削除し再度読ませようとするとエイリアスがかかった文章が読まれてしまうという不具合の修正。
ハッシュ値の生成元データをフォーマット済みテキストにすることで修正
> fix: 音声データの保存ハッシュ生成データ方式の修正

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Clear.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Disconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Ignore.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Restart.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Skip.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Summon.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Vcspeaker.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/AutoDisconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/AutoJoin.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/AutoMove.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_DeletedMessage.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_GoLiveNotify.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Join.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Move.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
- src/main/java/com/jaoafa/jdavcspeaker/Framework/Command/CmdRegister.java
- src/main/java/com/jaoafa/jdavcspeaker/Framework/Command/CmdSubstrate.java
- src/main/java/com/jaoafa/jdavcspeaker/Framework/Event/EventRegister.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibAlias.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibFlow.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibIgnore.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
- src/main/java/com/jaoafa/jdavcspeaker/Main.java
- src/main/java/com/jaoafa/jdavcspeaker/Player/TrackInfo.java
- src/main/java/com/jaoafa/jdavcspeaker/Player/TrackScheduler.java
- src/main/java/com/jaoafa/jdavcspeaker/StaticData.java
コミット分けるべきなんだけど、一つ始めたら連鎖的に修正しなきゃならんくなって分離できなかった…
`Lib/VoiceText` の filteringQueue 関数で定義
- VC退出時、参加・移動メッセージ読み上げを削除する
- GoLive終了時、GoLive開始読み上げを削除する
- タイトル変更時、タイトル変更通知読み上げを削除する（最新変更のみ通知）
の三つを追加したけど、テストした限りうまく動いているか微妙だった…。
あと、削除されたメッセージの読み上げをキャンセルする機能も追加。
自動読み上げキャンセルの追加に伴い、TrackInfo クラスに SpeakFromType 定数クラスを追加。
- `RECEIVED_MESSAGE`: 通常メッセージが送信された
- `RECEIVED_FILE`: ファイルが送信された
- `RECEIVED_IMAGE`: 画像が送信された
- `JOINED_VC`: VCにユーザーが参加した
- `MOVED_VC`: VCでユーザーが移動した
- `QUITED_VC`: VCからユーザーが退出した
- `STARTED_GOLIVE`: GoLiveを開始した
- `ENDED_GOLIVE`: GoLiveを終了した
- `CHANGED_TITLE`: VCタイトルを変えた
`java -jar jdavcspeaker-jar-with-dependencies.jar --only-remove-cmd` で登録済みコマンドをすべて削除してアプリケーションを終了する処理を行えるように。
動作テストをして最後にこれ実行しておけば本番環境に必要以上の被害を出さなくて済む
キーを `contain` と `equal` にしているせいで正常動作してないように見えたので、独立したリストで保持するように変更 …
> feat/fix: 機能追加 + 修正

- README.md
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java
close #86 
- #86 `/alias remove from:xxxx` 実行時に `java.util.MissingFormatArgumentException: Format specifier '%s'` が発生する問題の修正
- `/alias list page:n` の実装（実装が非常に汚いので今後リファクタリング）
- 上記実装に伴うREADME.mdの変更
> fix: #86 alias remove時に発生するformatエラーの修正、alias listをページネーションに対応

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_GeneralNotify.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/DefaultParamsManager.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibAlias.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibIgnore.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibJson.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibTitle.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/MultipleServer.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
close #94 
- 元タイトル: `🧀CheeseFactory`
- 実行コマンド: `/title test`
- 反映タイトル: `🧀test`
- (絵文字が実行タイトル内にある場合は元タイトルを引き継がない…はず)
`🍅test` って入れてるのに画像のようになってしまうので絵文字を入れた場合の動作が検証できてません
> feat: #94 titleコマンド実行時、新タイトルに絵文字が含まれていなかったら最初に絵文字を入れる

- pom.xml
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
close #101 
`https://twitter.com/book000/status/1457387013691244553` -> `Tomachiのツイート「タスク消化祭り」へのリンク`
> feat: #101 ツイートのリンクが張られたときにスクリーンネームとツイート内容を読み上げるように

- pom.xml
依存パッケージのアップデートを実施。
jda-utilitiesとか、bintrayがなくなった今どうしたらいいんですかね…？
> chore: 依存パッケージアップデート

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
close #113 
- :o: `https://twitter.com/book000/status/1468563877592178694`
- :x: `https://twitter.com/book000/status/1468563877592178694?s=20`
- :o: `https://twitter.com/book000/status/1468563877592178694`
- :o: `https://twitter.com/book000/status/1468563877592178694?s=20`
> fix: Twitterリンクにパラメーター(?...)が入っている場合に処理しない不具合を修正

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_StartNotify.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibFiles.java
- 鯖関係なくすべて `last-notify-id` から `start-notify-ids/{SERVER_iD}` に
> fix: vc開始通知のメッセージID記録ファイルの修正

- pom.xml
- src/main/java/com/jaoafa/jdavcspeaker/Main.java
https://github.com/jaoafa/JDA-VCSpeaker/pull/122#issuecomment-997234348 の修正
- Rollbarへのエラー送信が動作しない (途中まで動いていたのに動かなくなった)
- 取り合えず依存関係であるRollbarライブラリのアップデート実施、とはいえ相変わらず動かず
- `Thread.setDefaultUncaughtExceptionHandler` がもとの処理を完全上書きするということを忘れていて、標準エラー出力へのスタックトレースが出ない不具合を修正
- エラー時に #jda-vcspeaker-error に投げる
> fix: エラー処理を修正

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
pic.twitter.com を消したらうまくいきませんでした
あと自分へのアサインが外せません
> fix: ツイート読み上げ時、aリンク自体をそもそも消してしまう

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibTitle.java
- src/main/java/com/jaoafa/jdavcspeaker/Main.java
- チャンネル名の変更は10分に2回までの内部レートリミットが存在する
- JDAからAPI叩くとJDA側のRateLimiterのせいで動作が止まるので、直接生で叩くように変更
- title変更失敗した理由を返すように
> fix: titleコマンドによる変更を直接APIをたたいて変更するように

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Join.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Move.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibFiles.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/MsgFormatter.java
ユーザーがVCから抜けた場合、
1. チャット: `📤 TomachiBot が 🧀CheeseFactory(WorkingSpace) から退出しました。移動先を探しています…。`
2. 読み上げ: `TomachiBotがCheeseFactoryから退出しました。`
3. 移動先を検索
- 見つかった場合
1. チャット編集: `📤 TomachiBot が 🧀CheeseFactory(WorkingSpace) から退出し、Tomachi Discord の General に移動しました。`
2. 読み上げ: `TomachiBotはTomachi DiscordのGeneralに移動しました。`
- 見つからなかった場合
1. チャット編集: `📤 TomachiBot が 🧀CheeseFactory(WorkingSpace) から退出しました。`
> feat: 他サーバのVCに移動した場合にそれも通知するようにしてみる

- .gitignore
- pom.xml
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Ignore.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Summon.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Textimg.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/EmojiWrapper.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibIgnore.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibValue.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/MsgFormatter.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/UserVoiceTextResult.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/AttachmentsProcessor.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/BaseProcessor.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/CreatedThreadProcessor.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/DefaultMessageProcessor.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/ProcessorType.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/StickersProcessor.java
- src/main/java/com/jaoafa/jdavcspeaker/Player/TrackInfo.java
なんかちょこちょこいじったりしてたら色々混ざったプルリクになっちゃいました。申し訳ないです。
- 「メッセージ」と一言に言っても「ユーザから送られたメッセージ」・「Botから送られたメッセージ」・「ユーザが送ったシステムメッセージ」など様々なメッセージ形態があります。
- このようなさまざまな形態のメッセージに対応するため、「メッセージプロセッサ (MessageProcessor)」パッケージを生やしました。
- 現時点で、「ユーザーが送信したデフォルトメッセージ」・「スタンプ (Sticker) メッセージ」・「添付ファイル (メッセージ)」・「スレッド開始通知メッセージ (メッセージ派生かどうかを問わない)」に対応しています。
- TrackInfo.SpeakFromType に `RECEIVED_STICKER`, `CREATED_THREAD` を追加
- 画像内のテキストがあまりにも多い場合に2000文字を超えてしまいメッセージが送信できない不具合を修正。本文は1500文字で切り上げるように
- ignore 系の変数を LibValue から LibIgnore に移動
- IntelliJのインスペクション適用
- `Lib/EmojiWrapper` にて、 `EmojiManager::getByUnicode` が nullable なのにも関わらず適切な Null フィルタリングが行われていない問題の修正
- 正規表現 `[0-9]` を `\d` に置き換え
- 依存パッケージアップデート
- JDA: `5.0.0-alpha.11` → `5.0.0-alpha.12`
- org.json.json: `20210307` → `20220320`
close #163
ref #109
> refactor: メッセージ処理のリファクタリングなど

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_GoLiveNotify.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Join.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Move.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/AttachmentsProcessor.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/CreatedThreadProcessor.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/StickersProcessor.java
- close #177 
以下の作業を実施。
- titleコマンド: タイトルの変更時に発言するタイトルの前後にスペースを追加
- 誰かがVCに接続した時: ユーザ名とチャンネル名の前後にスペースを追加
- 誰かがVC移動した時: ユーザ名とチャンネル名の前後にスペースを追加
- 誰かがVCから切断した時: ユーザ名とチャンネル名の前後にスペースを追加
- GoLiveを開始した時: 開始時、ユーザー名の後にスペースを追加
- GoLiveを終了した時: 開始時、ユーザー名の後にスペースを追加
- 誰かが画像を送信した時: 画像テキストの後にスペースを追加
- 誰かがファイルを送信した時: ファイル名の前後にスペースを追加
- 誰かがスレッドを開始した時: ユーザ名とスレッド名の前後にスペースを追加
- 誰かがスタンプを送信した時: スタンプ名の前後にスペースを追加
> fix: ユーザー名やVC名などの前後にスペースを追加

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java
> fix: 移動先VCチャンネルを調べるときに、warnが表示されることで失敗するのでno-warningを追加

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Textimg.java
一部の環境（スマホ/タブレット？）で出てくる `media.discordapp.net` ドメインの画像リンクに対応します。
> feat(textimg): media.discordapp.netに対応

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Textimg.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/LibTextImg.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/AttachmentsProcessor.java
- close #185 
画像内テキストの返信時、textimgで出力されるテキスト位置が確認できる加工済み画像を自動添付するようになります。
また返信の形態を通常テキストからEmbedに変更します。
画像はこちらからお借りしました: https://twitter.com/nknknk1206/status/1595703786495827970
> feat: 画像投稿時、同時にtextimgの結果を返すようにする

- .github/workflows/release.yml
- pom.xml
- src/main/java/com/jaoafa/jdavcspeaker/Main.java
従来、git short hash をコードバージョンとして割り当てていましたが、#173 でビルド自体を GitHub Actions で行うようになったことに伴い、ホストサーバ側で git コマンドを叩いても git short hash が取得できなくなりました。
そのため、このプルリクエスト以降 pom.xml の version 値をコードバージョンとして使うように修正し、また関連する処理も修正します。
今回のプルリクエストで変更される点は以下の4つです。
- `Rollbar.init` 時、`codeVersion` として渡される値が `git rev-parse --short HEAD` コマンドの結果ではなく、`Main.class.getPackage().getImplementationVersion()` の返り値に変わります。
- `getImplementationVersion()` を使用するため、`maven-assembly-plugin` の `configuration.archive.manifest` の `addDefaultImplementationEntries` と `addDefaultSpecificationEntries` プロパティを `true` にします。これにより `pom.xml` の `version` プロパティの値が、成果物 jar にある `META-INF/MANIFEST.MF` に `Implementation-Version` へ書き込まれるようになります。
- リリース CI に `✏ Insert Version` の項目を追加。`mathieudutour/github-tag-action` が出力する …
> fix: rollbarに報告されるコードバージョンが不適切な問題を修正

- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
- src/main/java/com/jaoafa/jdavcspeaker/Main.java
- src/main/java/com/jaoafa/jdavcspeaker/Player/TrackScheduler.java
- close #184 
とあるユーザーがVCSpeakerをブロックしているようで、メッセージに対してリアクションをつけられずエラーが発生していました。このプルリクエストはこの問題の解決をします。
> fix: 当該ユーザーにブロックされているためにリアクションをつけられない場合にエラーを出さない

- src/main/java/com/jaoafa/jdavcspeaker/Player/TrackScheduler.java
- #145 
`queue` メソッド呼び出し時、`player.startTrack` の返り値がどうにも信頼できないので `this.queue` が空かどうかを判断するようにします。
ただ、これで #145 が改善されるわけではなく、APIからの音声データダウンロードの順番によって前後する問題があります。特にキャッシュがあるテキストの場合、ダウンロード中のテキストよりも先に読まれる可能性があります。
とはいえ、この改善で「キューが溜まっているのに(再生中なのに)割り込んで読まれる」ということはなくなるかと思います。
> fix: 音声をキュー挿入するかどうかの処理を調整

- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/DefaultMessageProcessor.java
URLが投稿された場合の読み上げについて、より聞き取りやすくなるように変更を加えました
「拡張子とそのファイルの名前が異なる場合（例: `jpg` 拡張子は `JPEGファイル` と読みたい）に extNameMap マップに定義しています。
定義されておらず、拡張子が取得できる場合は一律で `XXXファイル` (例: `png` 拡張子は `PNGファイル` と読むようになります。
拡張子がない場合は、`Webページへのリンク` と読みます。
> fix: いくつかの拡張子読み上げを修正

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/MsgFormatter.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/DefaultMessageProcessor.java
- `Message.getDisplayContent()` を使わずに、カスタムできる `getDisplayContent()` を作成
- エイリアスの適用タイミングを変更
- `/alias add` および `/alias remove`、`/alias list` 時の表示処理を調整し、絵文字のみの場合はその絵文字をそのまま表示するように
- ただし、Botが参加していないサーバのサーバ絵文字は表示できないためその旨を表記するように
> feat: 絵文字のエイリアスに対応

- pom.xml
以下の依存パッケージのアップデートを実施します。
- `com.squareup.okhttp3.okhttp`: `4.9.3` -> `4.10.0`
- `net.dv8tion.JDA`: `5.0.0-beta.5` -> `5.0.0-beta.8`
- `org.json.json`: `20220320` -> `20230227`
- `cloud.commandframework.cloud-jda`: `1.6.2` -> `1.8.3`
- `org.junit.jupiter.junit-jupiter`: `5.8.2` -> `5.9.2`
jaoafa/jao-Minecraft-Server#143 の解決を期待しますが、確実に解決する保証はありません。
> feat: JDAなどのアップデートを実施

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Clear.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Disconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Skip.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Vcspeaker.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/AutoDisconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_DeletedMessage.java
- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
- src/main/java/com/jaoafa/jdavcspeaker/Player/PlayerManager.java
- src/main/java/com/jaoafa/jdavcspeaker/Player/TrackScheduler.java
https://github.com/jaoafa/jao-Minecraft-Server/issues/143 の解決追加PRです。
- PlayerManager.destroy() 後にも継続して managers に当該キーが残り続けてるように見えたので、#209 をさらに追修正する形の内容となります。
- 読みやすくするため、PlayerManager にあるメソッドを全て static にしました。（内容的にわざわざインスタンスとして持っている理由が無いと判断）
- AutoDisconnected 後、必ずひとつ以上の読み上げキューが残る問題を暫定的に修正しました。これは同時に抜けた一般ユーザ分の退出読み上げが残るために起きる問題です。但し、同時に複数人がVCから抜けた場合この問題は必ず発生するので、根本的な設計部分 https://github.com/jaoafa/JDA-VCSpeaker/issues/145#issuecomment-1401153299 を実装し直さなければ直りません。
- デバッグ用として `/vcspeaker debug queue` を追加
絶対設計レベルからなんとかするべき問題がいくつかあるけど、私には時間がない…
> fix: PlayerManagerの完全static化、退出後の読み上げ停止

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java
MusicBotとかVCSpeaker本人が別のところにいる場合に出てきてしまうので…。
> feat: Botについては別鯖移動先検出をしないようにする

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Vcspeaker.java
以下2点の修正を実施します。https://github.com/jaoafa/jao-Minecraft-Server/issues/150 に関連
- `/vcspeaker server notify` と `/vcspeaker server remove` の機能が逆になっていた問題の修正（！？）
- `/vcspeaker server notify` に `channel` 引数を渡さないとき、チャンネル設定が解除されない問題の修正
> fix: vcspeaker serverコマンド周りの動作がおかしい問題修正

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java
#211 の実装により、Botに対しては移動検知をしなくなったことで以下のようなメッセージが残る問題を改善します。
> fix: 移動検知をしない場合に、「移動先を探しています…」が残る問題修正

- src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
- src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/DefaultMessageProcessor.java
- close #216 
---
- 太字のスロー読み上げを 1.75 から 1.30 に緩和
- `# ` から始まる文字列の場合、以下のフローで読み上げ処理を変更
- `#` がひとつ: 音量200% / 太字同様 1.30 の読み上げスピード低下
- `#` がふたつ: 音量175%
- `#` がみっつ: 音量150%
> feat: Markdownの見出し文字（#）に応じて音量とスピードを変更する

- src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
- src/main/java/com/jaoafa/jdavcspeaker/Lib/VCSpeakerArgs.java
- close https://github.com/jaoafa/JDA-VCSpeaker/issues/222
起動時に `--disable-auto-join-by-message` フラグをつけることで、以下の条件でVCSpeakerが参加する機能の無効化ができるようになります。
- vcテキストチャットへメッセージが投稿される
- 投稿者がどこかのvcにいる
- vcspeakerがvc参加していない
> feat: メッセージがVCテキストチャンネルに送信された場合に自動参加する機能の無効化オプションを追加

- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Vcname.java
- src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Vcspeaker.java
表題のとおり。
以下のコマンドで、必要とする権限のレベルを下げました。jaoであれば、モデレーターもこれらのコマンドが実行できるようになるはずです。
- `/vcspeaker` 関連のコマンド
- `/vcname save`, `/vcname saveall`
なお、この修正をせざるを得なくなったのはFrにVCSpeakerを導入したためです…
> feat: 一部のコマンドで管理者権限を必要としていたものをサーバ管理権限まで下げた

- src/main/java/com/jaoafa/jdavcspeaker/Event/AutoMove.java
close #232 
まだユーザがVCに滞在しているのに、AFKに移動したユーザーがいる場合、VCWatcherが退出してしまう問題を解決しました。  
あと少しで VCSpeaker.kt がいい感じになりそうなのでコードの整理とかはしてません。
> fix: disconnection when someone moves to afk
