jaoafa/JDA-VCSpeaker

src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
close #32 
`てえええ||ええええええええ||えええええすと` -> `てえええ ピー えええええすと`
=> feat: #32 スポイラーメッセージを「ピー」に置き換える。

README.md, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Default.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Ignore.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Join.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Move.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/DefaultParamsManager.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java, src/main/java/com/jaoafa/jdavcspeaker/Main.java
close #29 
- README.md に機能とコマンドの一覧を書きました
- `;default` コマンドを使用して、ユーザーのデフォルトパラメーターを指定できるようにしました
- VoiceText ライブラリを作り直しました
サーバ全体用の `default global` についてはのちほど。
=> feat: ユーザー毎にデフォルトパラメーターを指定できるように

.gitignore, pom.xml, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Debug.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Vcname.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SyncVCName.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibJson.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibTitle.java, src/main/java/com/jaoafa/jdavcspeaker/Main.java
=> feat: title

pom.xml
=> Upgrade JDA 4.2.1_265

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Skip.java
=> feat: #64 skipコマンドの実装

src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
close #71 
- ダウンロード中に :calling: をつける
- ハッシュ値の生成元データを `<読み上げ文章>_<スピーカー>_<スピード>_<エモーション>_<エモーションレベル>_<ピッチ>` に変更
- すでにダウンロード済みの場合、すぐ読み上げるように
=> feat: #71 VoiceTextからダウンロードしているときにリアクションをつける & ダウンロード済みの時の処理を修正

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java
=> fix: #67 オリジナルメッセージの取得をキュー処理する

src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java, src/main/java/com/jaoafa/jdavcspeaker/Main.java
close #55
```
**これはひどい**
**こ れ は ひ ど い**
こ　れ　は　ひ　ど　い
```
は対応したと思う
=> feat: #55 文章が強調されたときスピードを1/2にする（ベータ）

src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java
=> chore: Vision APIからのレスポンスを保存しておく

src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
=> fix: #86 絵文字を calling から eyes に変更

src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
=> fix: calling to eyes reaction

src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java
=> fix: 絵文字本体の変え忘れ

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibAlias.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibValue.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/MsgFormatter.java
close #21 
従来のすべてのエイリアスが正規表現として認識されますが、ピリオドだけのエイリアスとかはないので大丈夫でしょう。
=> feat: #21 エイリアスを正規表現で処理するように

pom.xml, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibReporter.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibValue.java, src/main/java/com/jaoafa/jdavcspeaker/Main.java
未キャッチの Exception、もしくは `LibReporter` に投げられた Exception を [rollbar](https://rollbar.com) に通知する
=> feat: rollbarでエラー収集

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibAlias.java
- `alias remove` の誤字修正 (コマンド実行者をAuthorに投げた)
- ![](https://i.imgur.com/oL0jDtd.png)
=> fix: 誤字脱字の修正、エイリアスパースをわかりやすくしたはず

src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Join.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Move.java
=> feat: #100 Botが入退出した際、読み上げはしないが投稿だけはする

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Default.java
close #99 
defaultコマンドにて、いまいち使いにくいっていう意見が多かったのでわかりやすいようにしました。ほぼクリック or 数字入力だけでイケルのでカーソルが勝手に動くことは(defaultコマンドでは)少なくなるかな？
=> feat: defaultコマンドにてspeakerやspeedなどをサジェストするように

src/main/java/com/jaoafa/jdavcspeaker/Player/TrackScheduler.java
というよりかは、リアクションをつけるときにエラーになる
```
|*|[DeletedMessage] メッセージ(ID: 906906725339267123)が削除されました。
net.dv8tion.jda.api.exceptions.ErrorResponseException: 10008: Unknown Message
at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:185)
at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:270)
at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:237)
at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:141)
at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:124)
at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(Bot …
```
=> fix: 投稿後、読み上げる際にメッセージが削除されている場合にエラーが発生する不具合の修正

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibAlias.java
ブランチ作り忘れたから名前変えようとしたのにブランチ名うまく変わんねえ…
=> fix: 長いエイリアスから処理するように変更

.gitignore, pom.xml, src/main/java/com/jaoafa/jdavcspeaker/Event/AutoJoin.java, src/main/java/com/jaoafa/jdavcspeaker/Event/AutoMove.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_GeneralNotify.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_GoLiveNotify.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Join.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Move.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/DefaultParamsManager.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibAlias.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibFiles.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibIgnore.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibTitle.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/MultipleServer.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/VCSpeakerArgs.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java, src/main/java/com/jaoafa/jdavcspeaker/Main.java
- 依存関係のバージョンアップ
- `MessageFormat.format` を `String.formatted` に変更
- LibFilesクラスを追加し、ファイル名の変更などを簡単にできるように + ファイル・ディレクトリの移動
- close #115 
- VoiceTextのキャッシュがなぜか削除されていたので該当コードを削除
いろいろ更新したので、細かくレビューをする必要があるかもしれません。何かあったら言ってください
=> リファクタリング & #115

src/main/java/com/jaoafa/jdavcspeaker/Lib/LibFiles.java
ローカルで試したときそんなことなかったのに！！！！！！！！！！！！！！！！！！！！！！！
=> fix: path.getNewPath().getParent()がnullになって起動しない不具合の修正

src/main/java/com/jaoafa/jdavcspeaker/Lib/MultipleServer.java
=> fix: 通知チャンネルがない場合にExceptionする不具合の修正

src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java
=> fix: 画像がポストされた場合にそのポストに対してなにも発言しない不具合の修正 (#116 関連)

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java
正規表現を追加する前にチェックするように
close #125
=> Fix: pattern syntax exception

src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
=> fix: ツイート読み上げ時、画像リンクの読み上げ処理を修正

src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java, src/main/resources/external_scripts/image-text.php
=> fix: #123 vision-api-resultsのパス修正

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Visionapi.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibFiles.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java
`/visionapi getlimit` でリミット関連の内容を返す
=> feat: visionapiコマンドを追加

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Skip.java
=> fix: #136 スキップコマンドが動作しない場合がある不具合の修正

src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
=> feat: #139 イベントリンクの読み上げと招待リンクの読み上げ処理追加

src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java
fix #147 
PCとIDE起動させるのめんどくさくてWebからいじったのでアレです
=> fix: 読み上げだけ30文字制限させる

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java
=> fix: #150 絵文字を指定しても絵文字が引き継がれてしまう問題の修正

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java
一部のユーザーに対しては日本語以外で返信します
関連:
- https://discord.com/channels/597378876556967936/623153228267388958/957094845325918219
- https://discord.com/channels/597378876556967936/623153228267388958/957094926598955038
- https://discord.com/channels/597378876556967936/623153228267388958/957097176662695976
=> feat: titleコマンド実行時のエラーをわかりやすくする

pom.xml, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Alias.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Clear.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Default.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Disconnect.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Ignore.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Restart.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Skip.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Summon.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Textimg.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Title.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Vcname.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Vcspeaker.java, src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Visionapi.java, src/main/java/com/jaoafa/jdavcspeaker/Event/Event_SpeakVCText.java, src/main/java/com/jaoafa/jdavcspeaker/Framework/Action/ActionSubstrate.java, src/main/java/com/jaoafa/jdavcspeaker/Framework/Command/CmdDetail.java, src/main/java/com/jaoafa/jdavcspeaker/Framework/Command/CmdRegister.java, src/main/java/com/jaoafa/jdavcspeaker/Framework/Command/CmdSubstrate.java, src/main/java/com/jaoafa/jdavcspeaker/Framework/FunctionContainer.java, src/main/java/com/jaoafa/jdavcspeaker/Framework/FunctionHooker.java, src/main/java/com/jaoafa/jdavcspeaker/Framework/FunctionSubstrate.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/LibReporter.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/MultipleServer.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/VCSpeakerArgs.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java, src/main/java/com/jaoafa/jdavcspeaker/Main.java
ref: [DV8FromTheWorld/JDA#1971](https://togithub.com/DV8FromTheWorld/JDA/pull/1971)
ブランチ名は気にしないで…。
=> fix: JDA v5.0.0-alpha.5で行われたインタラクションリワークへの対応

src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/ReplyProcessor.java
=> feat: リプライメッセージプロセッサの追加

src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/DefaultMessageProcessor.java, src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/ReplyProcessor.java
=> feat: リプライのメッセージ読み上げでどれへのリプライかを話すように

src/main/java/com/jaoafa/jdavcspeaker/Command/Cmd_Visionapi.java, src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java
close https://github.com/jaoafa/JDA-VCSpeaker/issues/165
=> feat: /visionapi getlimitで過去のデータを表示するように

src/main/java/com/jaoafa/jdavcspeaker/Lib/VoiceText.java, src/main/java/com/jaoafa/jdavcspeaker/Main.java, src/main/java/com/jaoafa/jdavcspeaker/Player/TrackScheduler.java
正確には、RestActionで発生するエラーをハンドリングできていない
=> feat: JDAが発するエラーをRollbarに送れていない問題の修正

src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/ProcessorType.java
=> fix: 画像付きのインラインリプライをした場合に画像情報が読み上げられない問題の修正

src/main/java/com/jaoafa/jdavcspeaker/Event/Event_Disconnect.java
=> chore: 移動先VCチャンネルチェック時の処理デバッグコード追加

src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/DefaultMessageProcessor.java
- close #193
[audio.zip](https://github.com/jaoafa/JDA-VCSpeaker/files/10324555/audio.zip)
=> fix: あまりにも遅すぎる太字読み上げを改善する

src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/DefaultMessageProcessor.java
- 次のファイルを指すURLが投稿されたとき、「～ファイルへのリンク」と読み上げる。ファイルは拡張子で判断する
- `jpg`: `JPEG 画像ファイル`
- `jpeg`: `JPEG 画像ファイル`
- `png`: `PNG 画像ファイル`
- `gif`: `GIF 画像ファイル`
- `mp4`: `MP4 動画ファイル`
- `mov`: `MOV 動画ファイル`
- `webm`: `WEBM 動画ファイル`
- `mp3`: `MP3 音声ファイル`
- `wav`: `WAV 音声ファイル`
- `ogg`: `OGG 音声ファイル`
- `flac`: `FLAC 音声ファイル`
- `txt`: `テキストファイル`
- `pdf`: `PDF ファイル`
- `doc`: `Word ファイル`
- `docx`: `Word ファイル`
- `xls`: `Excel ファイル`
- `xlsx`: `Excel ファイル`
- `ppt`: `PowerPoint ファイル`
- `pptx`: `PowerPoint ファイル`
- `zip`: `ZIP ファイル`
- `rar`: `RAR ファイル`
- `7z`: `7z ファイル`
- `tar`: `tar ファイル`
- `gz`: `gz ファイル`
- `xz`: `xz ファイル`
- `exe`: `実行ファイル`
- `jar`: `Java ファイル`
- `ps1`: `PowerShell スクリプトファイル`
- `bat`: `バッチファイル`
- `cmd`: `コマンドファイル`
- `sh`: `シェルスクリプトファイル`
- `js`: `JavaScript ファイル`
- `html`: `HTML ファイル`
- `htm`: `HTML …
=> feat: URL読み上げ時、拡張子で判断して読み上げるように。ツイート読み上げ関連も調整

src/main/java/com/jaoafa/jdavcspeaker/MessageProcessor/DefaultMessageProcessor.java
=> fix: 拡張子の取得処理を改善

src/main/java/com/jaoafa/jdavcspeaker/Event/AutoDisconnect.java, src/main/java/com/jaoafa/jdavcspeaker/Player/PlayerManager.java
=> feat: destroy player when automatic disconnection

src/main/java/com/jaoafa/jdavcspeaker/Event/AutoJoin.java, src/main/java/com/jaoafa/jdavcspeaker/Event/AutoMove.java
=> feat: AFKから別チャンネルに移動した場合に参加する

pom.xml
Raspberry Piなどで動かすため、arm64対応が必要だったので対応しました。
参考:
- https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md
- https://github.com/sedmelluq/lavaplayer/issues/622
- https://github.com/aikaterna/lavaplayer-natives
=> feat: arm64などの複数プラットフォームに対応

src/main/java/com/jaoafa/jdavcspeaker/Event/AutoMove.java
=> feat: 移動先がAFKで、移動元にBot以外0人になった場合は抜ける
